# Generated by Django 5.2.11 on 2026-02-16 07:53

from django.db import migrations


from django.contrib.postgres.operations import CreateExtension

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        # CreateExtension('vector'),
    ]
