# Generated by Django 5.2.11 on 2026-02-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_enable_pgvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="FontAwesome class (e.g., 'fas fa-code')", max_length=50),
        ),
    ]
