# Generated by Django 5.2.11 on 2026-02-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Django Blog', max_length=100)),
                ('primary_color', models.CharField(default='#2B7DDD', help_text='Hex code (e.g. #2B7DDD)', max_length=7)),
                ('background_color', models.CharField(default='#F3F4F6', help_text='Hex code (e.g. #F3F4F6)', max_length=7)),
                ('text_color', models.CharField(default='#1F2937', help_text='Hex code (e.g. #1F2937)', max_length=7)),
                ('link_color', models.CharField(default='#2563EB', help_text='Hex code (e.g. #2563EB)', max_length=7)),
                ('glass_opacity', models.DecimalField(decimal_places=2, default=0.7, help_text='0.0 to 1.0', max_digits=3)),
                ('glass_blur', models.IntegerField(default=10, help_text='Blur amount in px')),
                ('border_radius', models.CharField(default='1rem', help_text='e.g. 1rem, 16px', max_length=10)),
            ],
            options={
                'verbose_name': 'Theme Settings',
                'verbose_name_plural': 'Theme Settings',
            },
        ),
    ]
