# Generated by Django 5.2.11 on 2026-02-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_themesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Add any custom CSS here'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='enable_background_gradient',
            field=models.BooleanField(default=True, help_text='Enable the default fancy background gradient'),
        ),
    ]
