# Generated by Django 5.2.11 on 2026-02-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_themesettings_custom_css_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themesettings',
            name='custom_css',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='enable_background_gradient',
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO Description. Defaults to Description.'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords.', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO Title. Defaults to Name.', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO Description. Defaults to truncated content.'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords.', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO Title. Defaults to Title.', max_length=200),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='facebook_app_id',
            field=models.CharField(blank=True, help_text='Facebook App ID for Open Graph.', max_length=100),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='site_description',
            field=models.TextField(default='A modern Django blog.', help_text='Default meta description for the site.'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='site_keywords',
            field=models.CharField(default='django, blog, python, web development', help_text='Comma-separated keywords.', max_length=255),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='twitter_handle',
            field=models.CharField(blank=True, help_text='@yourhandle', max_length=100),
        ),
    ]
