# Generated by Django 5.2.11 on 2026-02-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='themesettings',
            name='email_active',
            field=models.BooleanField(default=False, help_text='Enable custom SMTP settings'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='email_from_email',
            field=models.EmailField(blank=True, help_text="Default 'From' email address", max_length=254),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='email_host',
            field=models.CharField(blank=True, help_text='SMTP Host (e.g., smtp.gmail.com)', max_length=255),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='SMTP Password', max_length=255),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='email_host_user',
            field=models.CharField(blank=True, help_text='SMTP Username', max_length=255),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='email_port',
            field=models.IntegerField(default=587, help_text='SMTP Port (e.g., 587)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='email_use_ssl',
            field=models.BooleanField(default=False, help_text='Use SSL'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Use TLS'),
        ),
    ]
