# Generated by Django 5.2.11 on 2026-02-18 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Navigation text', max_length=100)),
                ('link_type', models.CharField(choices=[('manual', 'Manual URL'), ('object', 'Internal Content (Post, Category, Tag, Page)')], default='manual', max_length=10)),
                ('url', models.CharField(blank=True, help_text='Used if link type is Manual', max_length=255)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to={'model__in': ('post', 'category', 'tag', 'pages', 'page', 'theme')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menus.menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menus.menuitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
